- name: Copy vpn up script
  template:
    src: openvpn/route_lan.py
    dest: "{{ openvpn.volumes.config.local_folder }}/up-route_lan.py"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  vars:
    action: I

- name: Copy vpn down script
  template:
    src: openvpn/route_lan.py
    dest: "{{ openvpn.volumes.config.local_folder }}/down-route_lan.py"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  vars:
    action: D

- name: Copy systemd oneshot service for configuring iptables
  template:
    src: openvpn/configure_vpn_iptables.service
    dest: /etc/systemd/system/configure_vpn_iptables.service
    mode: 0644

- name: Configure iptables for vpn using systemd (started, enabled)
  systemd:
    name: configure_vpn_iptables
    state: started
    enabled: yes
    daemon_reload: yes
  when: openvpn.use_host_net

- name: Configure iptables for vpn using systemd (stopped, disabled)
  systemd:
    name: configure_vpn_iptables
    state: stopped
    enabled: no
    daemon_reload: yes
  when: not openvpn.use_host_net
